theme: jekyll-theme-cayman
title: "SCS-based Analysis for the SARS-CoV-2 proteome"
description: "Supplementary Information for Article: *Self and nonself short constituent sequences of amino acids in the SARS-CoV-2 proteome for vaccine development*"
show_downloads: true
