theme: jekyll-theme-cayman
title: "SCS Application for ..."
description: "Supplementary Information for Article ''Self and nonself short constituent sequences of amino acids in the SARS-CoV-2 proteomes for vaccine development''"
show_downloads: true
